networks:
  default:
volumes:
  postgres-db-volume:

services:
  ckan-postgres:
    networks:
      - default
    image: "postgres:12"
    environment:
      POSTGRES_USER: ckan
      POSTGRES_PASSWORD: ckan

  ckan-redis:
    networks:
      - default
    image: "redis:3"

  ckan-solr:
    networks:
      - default
    image: "ckan/ckan-solr:master"

  ckan:
    image: python:3.9-bullseye
    networks:
      - default
    environment:
      HOME: /usr/src
      FMLD_DATASTORE_POSTGRES_DB: datastore_test
      FMLD_DATASTORE_POSTGRES_READ_USER: datastore_read
      FMLD_DATASTORE_POSTGRES_READ_PWD: pass
      FMLD_DATASTORE_POSTGRES_WRITE_USER: datastore_write
      FMLD_DATASTORE_POSTGRES_WRITE_PWD: pass
      FMLD_POSTGRES_DB: ckan_test
      FMLD_POSTGRES_USER: ckan_default
      FMLD_POSTGRES_PWD: pass
      PGPASSWORD: ckan
      PYTEST_COMMON_OPTIONS: -v --ckan-ini=test-core-circle-ci.ini --cov=ckan --cov=ckanext --junitxml=~/junit/junit.xml
      # report usage of deprecated features
      SQLALCHEMY_WARN_20: 1
    working_dir: "/usr/src"
    volumes:
      - "../:/usr/src"
    command: ["tail", "-f", "/etc/debian_version"]
